# Generated by Django 4.2.6 on 2023-10-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='cant_alun',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nom_prog',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='docente',
            name='seccion',
            field=models.CharField(max_length=5),
        ),
    ]
