# Generated by Django 4.2.6 on 2023-10-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_alter_docente_cant_alun_alter_docente_nom_prog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=300)),
                ('curso', models.CharField(max_length=200)),
                ('cred', models.CharField(max_length=5)),
                ('docente', models.CharField(max_length=150)),
                ('fecha_i', models.CharField(max_length=10)),
                ('fecha_f', models.CharField(max_length=10)),
                ('clases', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
    ]
